POST  http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"cibilex@cibilex.com",
    "password":"12345678"

}

###
GET http://localhost:8000/user/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaWJpbGV4QGNpYmlsZXguY29tIiwiaWF0IjoxNzA1ODQwNzg1fQ.PlET70DvLbsD61uL9F-B7REUooJ0ilawlFn9_KXIebUgH4wC432KPeQ0P0QxwO-azD_59z7QwBY4IVFu691kHWIuE0G3tc-m1DSpSwk0GMMSYOxtV97gVuSdcKCIK-VDNAiDvPkecIJ_mI2K8qKoCmzWuFf323K_tz7m56HDtmHwCknWIwdq74UtHL2uKm0f4HrYkL8O6qEO2A2gYNVSAJVk1fKhBkmW4TFG7dKVdfNSMiD-uwTI5Uj742ACfh0_USXgleV7eSGcpTnc5w6H6t6De3ZzxPujYOyOYe9D_NCIF46YOl_1oXI7fzFQfY3kLlmwOM-j7-PxlA9tJq6q0V6CKS7d1k5fHwIX-R-FOLZ-N-sC9d2TjEJUDYvNS68wjTweUy5wO9e6YzxaziN62SKtg7ygXkqRMteLPxSOznQIIW1F7oM4qVXyGVMAVOUWFTfOZW0b0NzLm3xoRXLZtx24UWWYEj9J7zECGICygFZa_w7xUkDEQmDW6eAcshde7gBri5fliQQEF92kKbbn2GbOHHC9YSWg2bw2nil_QIWj2kN4rLVPCUpzc3j0-M4AwAhzis3WmGzinSB_8cvw3VyuuikqpfQl8aTxz8W2IO6F7HvKsWMSfAjBYqDaYWui0sjaDgmNrjZmgWmGjBjy30cWgyzQn8zHy52K3oZkQg8





###
